// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dataAccess.Services;

#nullable disable

namespace dataAccess.Migrations.AiDb
{
    [DbContext(typeof(AiDbContext))]
    partial class AiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dataAccess.Entities.ChatFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feedback_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_feedback");

                    b.HasIndex("FeedbackType")
                        .HasDatabaseName("idx_chat_feedback_feedback_type");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("idx_chat_feedback_message_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_chat_feedback_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_chat_feedback_user_id");

                    b.ToTable("chat_feedback", "public");
                });

            modelBuilder.Entity("dataAccess.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Analysis")
                        .HasColumnType("text")
                        .HasColumnName("analysis");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Intent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intent");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<int?>("ResultRows")
                        .HasColumnType("integer")
                        .HasColumnName("result_rows");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_summary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<bool?>("SqlExecuted")
                        .HasColumnType("boolean")
                        .HasColumnName("sql_executed");

                    b.Property<string>("SqlGenerated")
                        .HasColumnType("text")
                        .HasColumnName("sql_generated");

                    b.Property<bool?>("SqlValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("sql_validated");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_chat_messages_created_at");

                    b.HasIndex("Intent")
                        .HasDatabaseName("idx_chat_messages_intent");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_chat_messages_session_id");

                    b.ToTable("chat_messages", "public");
                });

            modelBuilder.Entity("dataAccess.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PendingPlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("pending_plan_json");

                    b.Property<string>("PendingSlotName")
                        .HasColumnType("text")
                        .HasColumnName("pending_slot_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_chat_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_chat_sessions_user_id");

                    b.ToTable("chat_sessions", "public");
                });

            modelBuilder.Entity("dataAccess.Entities.FaqSearchLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnswerSnippet")
                        .HasColumnType("text")
                        .HasColumnName("answer_snippet");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Helpful")
                        .HasColumnType("boolean")
                        .HasColumnName("helpful");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_faq_search_logs");

                    b.ToTable("faq_search_logs", "public");
                });

            modelBuilder.Entity("dataAccess.Entities.ChatFeedback", b =>
                {
                    b.HasOne("dataAccess.Entities.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_feedback_chat_messages_message_id");

                    b.HasOne("dataAccess.Entities.ChatSession", "Session")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_feedback_chat_sessions_session_id");

                    b.Navigation("Message");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("dataAccess.Entities.ChatMessage", b =>
                {
                    b.HasOne("dataAccess.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("dataAccess.Entities.ChatSession", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
